# zmodload zsh/zprof

# I'm not sure what, but something is already setting this
# export PATH=/home/max/.local/bin:$PATH
# gpg-agent's ssh socket. Guarded and derived from XDG_RUNTIME_DIR rather than
# hardcoding uid 1000: pointing SSH_AUTH_SOCK at a socket that isn't there
# breaks ssh outright, including on machines that use plain ssh-agent.
_gpg_ssh_sock="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/gnupg/S.gpg-agent.ssh"
[[ -S $_gpg_ssh_sock ]] && export SSH_AUTH_SOCK=$_gpg_ssh_sock
unset _gpg_ssh_sock
export EDITOR='vim'
# IF I remove this, then my vim color is all green
export TERM="screen-256color"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

ZSH_TMUX_AUTOSTART=true;
ZSH_TMUX_AUTOCONNECT=true;

#### nvm
# Lazy loading defines node/npm/npx as shell *functions*, which child processes
# can't see — so nvim's mcp-hub build (and anything else shelling out to npm)
# fails with "Executable not found" even though nvm has a version installed.
# Put the newest installed version's bin on PATH directly: real binaries for
# children, no nvm.sh sourcing, no startup cost. (N) skips it when nvm is empty,
# om[1] picks the most recently installed version.
_node_bin=(~/.nvm/versions/node/*/bin(N/om[1]))
[[ -n $_node_bin ]] && path=($_node_bin $path)
unset _node_bin

# Lazy-load nvm: sourcing nvm.sh costs ~250ms at startup. lazy yes defers it
# until the first nvm/node/npm/etc. invocation. Autoload-on-cd via .nvmrc
# stops working in lazy mode — re-enable lazy no if you need that.
zstyle ':omz:plugins:nvm' lazy yes
# if I need to lazy load on commands other than node, npm, npx, pnpm, pnpx, yarn, or corepack, I can add those commands here
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript vim
# auto change node version based on .nvmrc
zstyle ':omz:plugins:nvm' autoload yes
zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading
#### /nvm


# disabling because I've lost track of what all these do. I'll turn them back on if I start to miss any
# zstyle ':completion:*' auto-description 'specify: %d'
# zstyle ':completion:*' completer _expand _complete _correct _approximate
# zstyle ':completion:*' format 'Completing %d'
# zstyle ':completion:*' group-name ''
# zstyle ':completion:*' menu select=2
# # Using omz lib now
# # eval "$(dircolors -b)"
# # doesn't seem do do anything
# # zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
# zstyle ':completion:*' menu select=long
# zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
# zstyle ':completion:*' use-compctl false
# zstyle ':completion:*' verbose true
# 
# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
# zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
# # set list-colors to enable filename colorizing
# # preview directory's content with exa when completing cd
# # disable sort when completing `git checkout`
# # zstyle ':completion:*:git-checkout:*' sort false
# # set descriptions format to enable group support
# zstyle ':completion:*:descriptions' format '[%d]'
# # set list-colors to enable filename colorizing
# zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# # preview directory's content with exa when completing cd
# zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'
# # switch group using `,` and `.`
# zstyle ':fzf-tab:*' switch-group ',' '.'

## disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
# I didn't like how tab was accepting
#zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'
# tell fzf tab we're light theme
zstyle ':fzf-tab:*' fzf-flags --color=light
# If you're using tmux >= 3.2, we provide a script ftb-tmux-popup to make full use of it's "popup" feature.
# really didn't like this
# zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

#### antidote
# Bootstrap on a fresh machine. Without this, every line below `source
# ~/.antidote/antidote.zsh` in this block fails and the shell comes up with no
# plugins, no completions and no prompt — antidote owns .zshrc.d too.
if [[ ! -e ~/.antidote/antidote.zsh ]]; then
  if (( $+commands[git] )); then
    print -u2 "zshrc: bootstrapping antidote into ~/.antidote"
    git clone --depth 1 https://github.com/mattmc3/antidote.git ~/.antidote
  else
    print -u2 "zshrc: ~/.antidote is missing and git isn't installed — running without plugins or prompt"
  fi
fi

if [[ -e ~/.antidote/antidote.zsh ]]; then
  source ~/.antidote/antidote.zsh
  # Set the root name of the plugins files (.txt and .zsh) antidote will use.
  zsh_plugins=${ZDOTDIR:-~}/.zsh_plugins

  # Ensure the .zsh_plugins.txt file exists so you can add plugins.
  [[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

  # Lazy-load antidote from its functions directory.
  fpath=(~/.antidote/functions $fpath)
  autoload -Uz antidote

  # Generate a new static file whenever .zsh_plugins.txt is updated.
  if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
    antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
  fi

  # Source your static plugins file.
  source ${zsh_plugins}.zsh
fi
#### /antidote

bindkey -v

# Cache task completion: `eval $(task --completion zsh)` execs `task` every
# startup (~20-30ms). Cache the output and regenerate when the task binary
# changes.
if (( $+commands[task] )); then
  _task_completion_cache="${ZSH_CACHE_DIR:-$HOME/.cache/zsh}/task-completion.zsh"
  if [[ ! -s $_task_completion_cache || $commands[task] -nt $_task_completion_cache ]]; then
    mkdir -p ${_task_completion_cache:h}
    task --completion zsh >| $_task_completion_cache
  fi
  source $_task_completion_cache
  unset _task_completion_cache
fi

export GPG_TTY="${TTY}"

# Only prepend dirs that exist, so $PATH doesn't collect phantom entries on a
# machine that never installed the tool. (None of these three exist here.)
for _dir in $HOME/.bin $HOME/.local/share/coursier/bin ${KREW_ROOT:-$HOME/.krew}/bin; do
  [[ -d $_dir ]] && path=($_dir $path)
done
unset _dir


export DEBFULLNAME="Max Mizikar"
export DEBEMAIL="maxmzkr@gmail.com"

# Uses the command-not-found package zsh support
# as seen in https://www.porcheron.info/command-not-found-for-zsh/
# this is installed in Ubuntu

if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
    function command_not_found_handler {
        # check because c-n-f could've been removed in the meantime
        if [ -x /usr/lib/command-not-found ]; then
            /usr/lib/command-not-found -- "$1"
            return $?
        elif [ -x /usr/share/command-not-found/command-not-found ]; then
            /usr/share/command-not-found/command-not-found -- "$1"
            return $?
        else
            printf "zsh: command not found: %s\n" "$1" >&2
            return 127
        fi
        return 0
    }
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias ipdb='ipdb3 '
alias sudo='nocorrect sudo '
alias watch='watch '

notif () {
    $@ && paplay /usr/share/sounds/gnome/default/alerts/bark.ogg
}

# function to set the title of the current tab
function set-title() {
  printf '\e]2;'"${1}"'\a'
}

# function to start tmux and set title
function new-ses() {
  tmux new -s $1
  set-title $1
}

# allow for ctrl+arrow movement
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

ENVSDIR="${HOME}"'/.venvs'

function venv() {
    source "${ENVSDIR}"'/'"${1}"'/bin/activate'
}

function makevenv() {
    "${1}" -m venv "${ENVSDIR}"'/'"${2}"
}

function vf() {
    ls -d "${ENVSDIR}"'/'*'/' | fzf | while read file; do source $file/bin/activate; done
}

# I haven't been using the salt states anymore
# function sf() {
#     sudo echo || exit 1
#     state_lookup=$(sudo salt-call --local state.show_highstate --output yaml | yq e '.local as $top | .local | keys | .[] | {.: $top[.].__sls__}' -)
#     all_sls=$(echo "${state_lookup}" | yq e '.[]' - | sort | uniq | paste -sd "," -)
#     echo "${state_lookup}" | yq e 'keys | .[]' - | fzf | while read state;
#     do
#         print -s 'sudo salt-call --local --log-level debug state.sls_id '"${state}"' '"${all_sls}";
#         sudo salt-call --local --log-level debug state.sls_id "${state}" "${all_sls}";
#     done
# }

# if systemctl --user status docker.service > /dev/null; then
# 	export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
# fi


# Undo rm alias from ohmyzsh common-aliases
# alias rm="rm -I"

# kubectl aliases
alias kg='kubectl get'
alias kgj='kubectl get jobs'
alias kd='kubectl describe'
alias kw='kubectl wait'

# git aliases
alias gcr='current_branch'
alias gmt='git mergetool --no-promt'
alias gcpt='git commit -p'

# docker
# alias docker=podman

# `terraform` lives at /snap/bin/terraform (the old tfenv path was stale).
# `complete -C` needs bashcompinit, which the nvm plugin already autoloads — so
# check for it, since it's gone if plugin loading failed.
if (( $+commands[terraform] && $+functions[complete] )); then
  complete -o nospace -C ${commands[terraform]} terraform
fi

export USE_GKE_GCLOUD_AUTH_PLUGIN=True

if command -v pyenv &> /dev/null
then
  eval "$(pyenv virtualenv-init -)"
fi
# linuxbrew (absent on this machine — the exports used to run unconditionally)
if [[ -d /home/linuxbrew/.linuxbrew ]]; then
  export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
  export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
  export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
  export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
  export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
  export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";
fi

# Machine-specific and untracked; the dircolors block above already falls back to
# `dircolors -b` defaults, so just skip this when the file isn't there.
[[ -r ~/.dir_colors/dircolors ]] && eval $(dircolors ~/.dir_colors/dircolors)

# Don't alias vim away to a binary that isn't installed yet.
if (( $+commands[nvim] )); then
  alias vim='nvim'
  export KUBE_EDITOR=nvim
fi

if command -v jenv &> /dev/null
then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
fi

# tenv. `current` follows the snap revision — the old hardcoded /snap/tenv/292
# is gone on this machine already.
[[ -d /snap/tenv/current ]] && path=(/snap/tenv/current $path)

# zprof

# Lazy-load gvm: sourcing ~/.gvm/scripts/gvm costs ~230ms (it overrides
# `cd` and pre-loads env files). Defer until the first `gvm` call. Note: this
# DROPS gvm's automatic GOROOT/GOPATH switching on `cd` — fine because system
# `go` is in PATH and the cd override was the slowest part.
if [[ -s ~/.gvm/scripts/gvm ]]; then
  gvm() {
    unfunction gvm
    source ~/.gvm/scripts/gvm
    gvm "$@"
  }
fi
